/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HostReviewsRouteImport } from './routes/host.reviews'
import { Route as HostRevenueRouteImport } from './routes/host.revenue'
import { Route as HostProfileRouteImport } from './routes/host.profile'
import { Route as HostExperiencesRouteImport } from './routes/host.experiences'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as HostBookingsRouteImport } from './routes/host.bookings'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard.wishlist'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPastRouteImport } from './routes/dashboard.past'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardCartRouteImport } from './routes/dashboard.cart'
import { Route as DashboardCancelledRouteImport } from './routes/dashboard.cancelled'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminHomepageEditRouteImport } from './routes/admin.homepage-edit'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as HostExperiencesIndexRouteImport } from './routes/host.experiences.index'
import { Route as HostBookingsIndexRouteImport } from './routes/host.bookings.index'
import { Route as ExperiencesSlugIndexRouteImport } from './routes/experiences.$slug.index'
import { Route as DashboardCartIndexRouteImport } from './routes/dashboard.cart.index'
import { Route as BookingsBookingIdIndexRouteImport } from './routes/bookings.$bookingId.index'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin.reviews.index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin.profile.index'
import { Route as AdminHostsIndexRouteImport } from './routes/admin.hosts.index'
import { Route as AdminExperiencesIndexRouteImport } from './routes/admin.experiences.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminActivityIndexRouteImport } from './routes/admin.activity.index'
import { Route as HostExperiencesNewRouteImport } from './routes/host.experiences.new'
import { Route as HostExperiencesExperienceIdRouteImport } from './routes/host.experiences.$experienceId'
import { Route as HostBookingsBookingIdRouteImport } from './routes/host.bookings.$bookingId'
import { Route as ExperiencesSlugBookRouteImport } from './routes/experiences.$slug.book'
import { Route as BookingsBookingIdReviewRouteImport } from './routes/bookings.$bookingId.review'
import { Route as AdminProfileHomepagePhotosRouteImport } from './routes/admin.profile.homepage-photos'
import { Route as AdminExperiencesExperienceIdRouteImport } from './routes/admin.experiences.$experienceId'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin.bookings.$bookingId'
import { Route as DashboardCartCheckoutSlugRouteImport } from './routes/dashboard.cart.checkout.$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperiencesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HostReviewsRoute = HostReviewsRouteImport.update({
  id: '/host/reviews',
  path: '/host/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRevenueRoute = HostRevenueRouteImport.update({
  id: '/host/revenue',
  path: '/host/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const HostProfileRoute = HostProfileRouteImport.update({
  id: '/host/profile',
  path: '/host/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HostExperiencesRoute = HostExperiencesRouteImport.update({
  id: '/host/experiences',
  path: '/host/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostBookingsRoute = HostBookingsRouteImport.update({
  id: '/host/bookings',
  path: '/host/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPastRoute = DashboardPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartRoute = DashboardCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCancelledRoute = DashboardCancelledRouteImport.update({
  id: '/cancelled',
  path: '/cancelled',
  getParentRoute: () => DashboardRoute,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CitiesRoute,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageEditRoute = AdminHomepageEditRouteImport.update({
  id: '/homepage-edit',
  path: '/homepage-edit',
  getParentRoute: () => AdminRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HostExperiencesIndexRoute = HostExperiencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostExperiencesRoute,
} as any)
const HostBookingsIndexRoute = HostBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostBookingsRoute,
} as any)
const ExperiencesSlugIndexRoute = ExperiencesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperiencesSlugRoute,
} as any)
const DashboardCartIndexRoute = DashboardCartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCartRoute,
} as any)
const BookingsBookingIdIndexRoute = BookingsBookingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProfileRoute,
} as any)
const AdminHostsIndexRoute = AdminHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesIndexRoute = AdminExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityIndexRoute = AdminActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AdminRoute,
} as any)
const HostExperiencesNewRoute = HostExperiencesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostExperiencesRoute,
} as any)
const HostExperiencesExperienceIdRoute =
  HostExperiencesExperienceIdRouteImport.update({
    id: '/$experienceId',
    path: '/$experienceId',
    getParentRoute: () => HostExperiencesRoute,
  } as any)
const HostBookingsBookingIdRoute = HostBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => HostBookingsRoute,
} as any)
const ExperiencesSlugBookRoute = ExperiencesSlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ExperiencesSlugRoute,
} as any)
const BookingsBookingIdReviewRoute = BookingsBookingIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)
const AdminProfileHomepagePhotosRoute =
  AdminProfileHomepagePhotosRouteImport.update({
    id: '/homepage-photos',
    path: '/homepage-photos',
    getParentRoute: () => AdminProfileRoute,
  } as any)
const AdminExperiencesExperienceIdRoute =
  AdminExperiencesExperienceIdRouteImport.update({
    id: '/experiences/$experienceId',
    path: '/experiences/$experienceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardCartCheckoutSlugRoute =
  DashboardCartCheckoutSlugRouteImport.update({
    id: '/checkout/$slug',
    path: '/checkout/$slug',
    getParentRoute: () => DashboardCartRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/hosts': typeof HostsRoute
  '/journal': typeof JournalRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/homepage-edit': typeof AdminHomepageEditRoute
  '/admin/profile': typeof AdminProfileRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/cities/$slug': typeof CitiesSlugRoute
  '/dashboard/cancelled': typeof DashboardCancelledRoute
  '/dashboard/cart': typeof DashboardCartRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/past': typeof DashboardPastRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/host/bookings': typeof HostBookingsRouteWithChildren
  '/host/dashboard': typeof HostDashboardRoute
  '/host/experiences': typeof HostExperiencesRouteWithChildren
  '/host/profile': typeof HostProfileRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/experiences/$experienceId': typeof AdminExperiencesExperienceIdRoute
  '/admin/profile/homepage-photos': typeof AdminProfileHomepagePhotosRoute
  '/bookings/$bookingId/review': typeof BookingsBookingIdReviewRoute
  '/experiences/$slug/book': typeof ExperiencesSlugBookRoute
  '/host/bookings/$bookingId': typeof HostBookingsBookingIdRoute
  '/host/experiences/$experienceId': typeof HostExperiencesExperienceIdRoute
  '/host/experiences/new': typeof HostExperiencesNewRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/hosts/': typeof AdminHostsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/dashboard/cart/': typeof DashboardCartIndexRoute
  '/experiences/$slug/': typeof ExperiencesSlugIndexRoute
  '/host/bookings/': typeof HostBookingsIndexRoute
  '/host/experiences/': typeof HostExperiencesIndexRoute
  '/dashboard/cart/checkout/$slug': typeof DashboardCartCheckoutSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/journal': typeof JournalRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/homepage-edit': typeof AdminHomepageEditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/dashboard/cancelled': typeof DashboardCancelledRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/past': typeof DashboardPastRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/profile': typeof HostProfileRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/experiences/$experienceId': typeof AdminExperiencesExperienceIdRoute
  '/admin/profile/homepage-photos': typeof AdminProfileHomepagePhotosRoute
  '/bookings/$bookingId/review': typeof BookingsBookingIdReviewRoute
  '/experiences/$slug/book': typeof ExperiencesSlugBookRoute
  '/host/bookings/$bookingId': typeof HostBookingsBookingIdRoute
  '/host/experiences/$experienceId': typeof HostExperiencesExperienceIdRoute
  '/host/experiences/new': typeof HostExperiencesNewRoute
  '/admin/activity': typeof AdminActivityIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/experiences': typeof AdminExperiencesIndexRoute
  '/admin/hosts': typeof AdminHostsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/bookings/$bookingId': typeof BookingsBookingIdIndexRoute
  '/dashboard/cart': typeof DashboardCartIndexRoute
  '/experiences/$slug': typeof ExperiencesSlugIndexRoute
  '/host/bookings': typeof HostBookingsIndexRoute
  '/host/experiences': typeof HostExperiencesIndexRoute
  '/dashboard/cart/checkout/$slug': typeof DashboardCartCheckoutSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/hosts': typeof HostsRoute
  '/journal': typeof JournalRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/homepage-edit': typeof AdminHomepageEditRoute
  '/admin/profile': typeof AdminProfileRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/cities/$slug': typeof CitiesSlugRoute
  '/dashboard/cancelled': typeof DashboardCancelledRoute
  '/dashboard/cart': typeof DashboardCartRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/past': typeof DashboardPastRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/host/bookings': typeof HostBookingsRouteWithChildren
  '/host/dashboard': typeof HostDashboardRoute
  '/host/experiences': typeof HostExperiencesRouteWithChildren
  '/host/profile': typeof HostProfileRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/experiences/$experienceId': typeof AdminExperiencesExperienceIdRoute
  '/admin/profile/homepage-photos': typeof AdminProfileHomepagePhotosRoute
  '/bookings/$bookingId/review': typeof BookingsBookingIdReviewRoute
  '/experiences/$slug/book': typeof ExperiencesSlugBookRoute
  '/host/bookings/$bookingId': typeof HostBookingsBookingIdRoute
  '/host/experiences/$experienceId': typeof HostExperiencesExperienceIdRoute
  '/host/experiences/new': typeof HostExperiencesNewRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/hosts/': typeof AdminHostsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/dashboard/cart/': typeof DashboardCartIndexRoute
  '/experiences/$slug/': typeof ExperiencesSlugIndexRoute
  '/host/bookings/': typeof HostBookingsIndexRoute
  '/host/experiences/': typeof HostExperiencesIndexRoute
  '/dashboard/cart/checkout/$slug': typeof DashboardCartCheckoutSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cities'
    | '/contact'
    | '/dashboard'
    | '/experiences'
    | '/hosts'
    | '/journal'
    | '/sign-in'
    | '/sign-up'
    | '/account/profile'
    | '/admin/homepage-edit'
    | '/admin/profile'
    | '/auth/callback'
    | '/bookings/$bookingId'
    | '/cities/$slug'
    | '/dashboard/cancelled'
    | '/dashboard/cart'
    | '/dashboard/history'
    | '/dashboard/past'
    | '/dashboard/profile'
    | '/dashboard/wishlist'
    | '/experiences/$slug'
    | '/host/bookings'
    | '/host/dashboard'
    | '/host/experiences'
    | '/host/profile'
    | '/host/revenue'
    | '/host/reviews'
    | '/admin/'
    | '/dashboard/'
    | '/experiences/'
    | '/admin/bookings/$bookingId'
    | '/admin/experiences/$experienceId'
    | '/admin/profile/homepage-photos'
    | '/bookings/$bookingId/review'
    | '/experiences/$slug/book'
    | '/host/bookings/$bookingId'
    | '/host/experiences/$experienceId'
    | '/host/experiences/new'
    | '/admin/activity/'
    | '/admin/bookings/'
    | '/admin/experiences/'
    | '/admin/hosts/'
    | '/admin/profile/'
    | '/admin/reviews/'
    | '/bookings/$bookingId/'
    | '/dashboard/cart/'
    | '/experiences/$slug/'
    | '/host/bookings/'
    | '/host/experiences/'
    | '/dashboard/cart/checkout/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cities'
    | '/contact'
    | '/hosts'
    | '/journal'
    | '/sign-in'
    | '/sign-up'
    | '/account/profile'
    | '/admin/homepage-edit'
    | '/auth/callback'
    | '/cities/$slug'
    | '/dashboard/cancelled'
    | '/dashboard/history'
    | '/dashboard/past'
    | '/dashboard/profile'
    | '/dashboard/wishlist'
    | '/host/dashboard'
    | '/host/profile'
    | '/host/revenue'
    | '/host/reviews'
    | '/admin'
    | '/dashboard'
    | '/experiences'
    | '/admin/bookings/$bookingId'
    | '/admin/experiences/$experienceId'
    | '/admin/profile/homepage-photos'
    | '/bookings/$bookingId/review'
    | '/experiences/$slug/book'
    | '/host/bookings/$bookingId'
    | '/host/experiences/$experienceId'
    | '/host/experiences/new'
    | '/admin/activity'
    | '/admin/bookings'
    | '/admin/experiences'
    | '/admin/hosts'
    | '/admin/profile'
    | '/admin/reviews'
    | '/bookings/$bookingId'
    | '/dashboard/cart'
    | '/experiences/$slug'
    | '/host/bookings'
    | '/host/experiences'
    | '/dashboard/cart/checkout/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cities'
    | '/contact'
    | '/dashboard'
    | '/experiences'
    | '/hosts'
    | '/journal'
    | '/sign-in'
    | '/sign-up'
    | '/account/profile'
    | '/admin/homepage-edit'
    | '/admin/profile'
    | '/auth/callback'
    | '/bookings/$bookingId'
    | '/cities/$slug'
    | '/dashboard/cancelled'
    | '/dashboard/cart'
    | '/dashboard/history'
    | '/dashboard/past'
    | '/dashboard/profile'
    | '/dashboard/wishlist'
    | '/experiences/$slug'
    | '/host/bookings'
    | '/host/dashboard'
    | '/host/experiences'
    | '/host/profile'
    | '/host/revenue'
    | '/host/reviews'
    | '/admin/'
    | '/dashboard/'
    | '/experiences/'
    | '/admin/bookings/$bookingId'
    | '/admin/experiences/$experienceId'
    | '/admin/profile/homepage-photos'
    | '/bookings/$bookingId/review'
    | '/experiences/$slug/book'
    | '/host/bookings/$bookingId'
    | '/host/experiences/$experienceId'
    | '/host/experiences/new'
    | '/admin/activity/'
    | '/admin/bookings/'
    | '/admin/experiences/'
    | '/admin/hosts/'
    | '/admin/profile/'
    | '/admin/reviews/'
    | '/bookings/$bookingId/'
    | '/dashboard/cart/'
    | '/experiences/$slug/'
    | '/host/bookings/'
    | '/host/experiences/'
    | '/dashboard/cart/checkout/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitiesRoute: typeof CitiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  HostsRoute: typeof HostsRoute
  JournalRoute: typeof JournalRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRouteWithChildren
  HostBookingsRoute: typeof HostBookingsRouteWithChildren
  HostDashboardRoute: typeof HostDashboardRoute
  HostExperiencesRoute: typeof HostExperiencesRouteWithChildren
  HostProfileRoute: typeof HostProfileRoute
  HostRevenueRoute: typeof HostRevenueRoute
  HostReviewsRoute: typeof HostReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/host/reviews': {
      id: '/host/reviews'
      path: '/host/reviews'
      fullPath: '/host/reviews'
      preLoaderRoute: typeof HostReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/revenue': {
      id: '/host/revenue'
      path: '/host/revenue'
      fullPath: '/host/revenue'
      preLoaderRoute: typeof HostRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/profile': {
      id: '/host/profile'
      path: '/host/profile'
      fullPath: '/host/profile'
      preLoaderRoute: typeof HostProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/experiences': {
      id: '/host/experiences'
      path: '/host/experiences'
      fullPath: '/host/experiences'
      preLoaderRoute: typeof HostExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/bookings': {
      id: '/host/bookings'
      path: '/host/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof HostBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/past': {
      id: '/dashboard/past'
      path: '/past'
      fullPath: '/dashboard/past'
      preLoaderRoute: typeof DashboardPastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart': {
      id: '/dashboard/cart'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof DashboardCartRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cancelled': {
      id: '/dashboard/cancelled'
      path: '/cancelled'
      fullPath: '/dashboard/cancelled'
      preLoaderRoute: typeof DashboardCancelledRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage-edit': {
      id: '/admin/homepage-edit'
      path: '/homepage-edit'
      fullPath: '/admin/homepage-edit'
      preLoaderRoute: typeof AdminHomepageEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/experiences/': {
      id: '/host/experiences/'
      path: '/'
      fullPath: '/host/experiences/'
      preLoaderRoute: typeof HostExperiencesIndexRouteImport
      parentRoute: typeof HostExperiencesRoute
    }
    '/host/bookings/': {
      id: '/host/bookings/'
      path: '/'
      fullPath: '/host/bookings/'
      preLoaderRoute: typeof HostBookingsIndexRouteImport
      parentRoute: typeof HostBookingsRoute
    }
    '/experiences/$slug/': {
      id: '/experiences/$slug/'
      path: '/'
      fullPath: '/experiences/$slug/'
      preLoaderRoute: typeof ExperiencesSlugIndexRouteImport
      parentRoute: typeof ExperiencesSlugRoute
    }
    '/dashboard/cart/': {
      id: '/dashboard/cart/'
      path: '/'
      fullPath: '/dashboard/cart/'
      preLoaderRoute: typeof DashboardCartIndexRouteImport
      parentRoute: typeof DashboardCartRoute
    }
    '/bookings/$bookingId/': {
      id: '/bookings/$bookingId/'
      path: '/'
      fullPath: '/bookings/$bookingId/'
      preLoaderRoute: typeof BookingsBookingIdIndexRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminProfileRoute
    }
    '/admin/hosts/': {
      id: '/admin/hosts/'
      path: '/hosts'
      fullPath: '/admin/hosts/'
      preLoaderRoute: typeof AdminHostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/': {
      id: '/admin/experiences/'
      path: '/experiences'
      fullPath: '/admin/experiences/'
      preLoaderRoute: typeof AdminExperiencesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity/': {
      id: '/admin/activity/'
      path: '/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AdminActivityIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/host/experiences/new': {
      id: '/host/experiences/new'
      path: '/new'
      fullPath: '/host/experiences/new'
      preLoaderRoute: typeof HostExperiencesNewRouteImport
      parentRoute: typeof HostExperiencesRoute
    }
    '/host/experiences/$experienceId': {
      id: '/host/experiences/$experienceId'
      path: '/$experienceId'
      fullPath: '/host/experiences/$experienceId'
      preLoaderRoute: typeof HostExperiencesExperienceIdRouteImport
      parentRoute: typeof HostExperiencesRoute
    }
    '/host/bookings/$bookingId': {
      id: '/host/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/host/bookings/$bookingId'
      preLoaderRoute: typeof HostBookingsBookingIdRouteImport
      parentRoute: typeof HostBookingsRoute
    }
    '/experiences/$slug/book': {
      id: '/experiences/$slug/book'
      path: '/book'
      fullPath: '/experiences/$slug/book'
      preLoaderRoute: typeof ExperiencesSlugBookRouteImport
      parentRoute: typeof ExperiencesSlugRoute
    }
    '/bookings/$bookingId/review': {
      id: '/bookings/$bookingId/review'
      path: '/review'
      fullPath: '/bookings/$bookingId/review'
      preLoaderRoute: typeof BookingsBookingIdReviewRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/admin/profile/homepage-photos': {
      id: '/admin/profile/homepage-photos'
      path: '/homepage-photos'
      fullPath: '/admin/profile/homepage-photos'
      preLoaderRoute: typeof AdminProfileHomepagePhotosRouteImport
      parentRoute: typeof AdminProfileRoute
    }
    '/admin/experiences/$experienceId': {
      id: '/admin/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/admin/experiences/$experienceId'
      preLoaderRoute: typeof AdminExperiencesExperienceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/cart/checkout/$slug': {
      id: '/dashboard/cart/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/dashboard/cart/checkout/$slug'
      preLoaderRoute: typeof DashboardCartCheckoutSlugRouteImport
      parentRoute: typeof DashboardCartRoute
    }
  }
}

interface AdminProfileRouteChildren {
  AdminProfileHomepagePhotosRoute: typeof AdminProfileHomepagePhotosRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
}

const AdminProfileRouteChildren: AdminProfileRouteChildren = {
  AdminProfileHomepagePhotosRoute: AdminProfileHomepagePhotosRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
}

const AdminProfileRouteWithChildren = AdminProfileRoute._addFileChildren(
  AdminProfileRouteChildren,
)

interface AdminRouteChildren {
  AdminHomepageEditRoute: typeof AdminHomepageEditRoute
  AdminProfileRoute: typeof AdminProfileRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminExperiencesExperienceIdRoute: typeof AdminExperiencesExperienceIdRoute
  AdminActivityIndexRoute: typeof AdminActivityIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminExperiencesIndexRoute: typeof AdminExperiencesIndexRoute
  AdminHostsIndexRoute: typeof AdminHostsIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHomepageEditRoute: AdminHomepageEditRoute,
  AdminProfileRoute: AdminProfileRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminExperiencesExperienceIdRoute: AdminExperiencesExperienceIdRoute,
  AdminActivityIndexRoute: AdminActivityIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminExperiencesIndexRoute: AdminExperiencesIndexRoute,
  AdminHostsIndexRoute: AdminHostsIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitiesRouteChildren {
  CitiesSlugRoute: typeof CitiesSlugRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesSlugRoute: CitiesSlugRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface DashboardCartRouteChildren {
  DashboardCartIndexRoute: typeof DashboardCartIndexRoute
  DashboardCartCheckoutSlugRoute: typeof DashboardCartCheckoutSlugRoute
}

const DashboardCartRouteChildren: DashboardCartRouteChildren = {
  DashboardCartIndexRoute: DashboardCartIndexRoute,
  DashboardCartCheckoutSlugRoute: DashboardCartCheckoutSlugRoute,
}

const DashboardCartRouteWithChildren = DashboardCartRoute._addFileChildren(
  DashboardCartRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCancelledRoute: typeof DashboardCancelledRoute
  DashboardCartRoute: typeof DashboardCartRouteWithChildren
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardPastRoute: typeof DashboardPastRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCancelledRoute: DashboardCancelledRoute,
  DashboardCartRoute: DashboardCartRouteWithChildren,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardPastRoute: DashboardPastRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ExperiencesSlugRouteChildren {
  ExperiencesSlugBookRoute: typeof ExperiencesSlugBookRoute
  ExperiencesSlugIndexRoute: typeof ExperiencesSlugIndexRoute
}

const ExperiencesSlugRouteChildren: ExperiencesSlugRouteChildren = {
  ExperiencesSlugBookRoute: ExperiencesSlugBookRoute,
  ExperiencesSlugIndexRoute: ExperiencesSlugIndexRoute,
}

const ExperiencesSlugRouteWithChildren = ExperiencesSlugRoute._addFileChildren(
  ExperiencesSlugRouteChildren,
)

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRouteWithChildren
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRouteWithChildren,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface BookingsBookingIdRouteChildren {
  BookingsBookingIdReviewRoute: typeof BookingsBookingIdReviewRoute
  BookingsBookingIdIndexRoute: typeof BookingsBookingIdIndexRoute
}

const BookingsBookingIdRouteChildren: BookingsBookingIdRouteChildren = {
  BookingsBookingIdReviewRoute: BookingsBookingIdReviewRoute,
  BookingsBookingIdIndexRoute: BookingsBookingIdIndexRoute,
}

const BookingsBookingIdRouteWithChildren =
  BookingsBookingIdRoute._addFileChildren(BookingsBookingIdRouteChildren)

interface HostBookingsRouteChildren {
  HostBookingsBookingIdRoute: typeof HostBookingsBookingIdRoute
  HostBookingsIndexRoute: typeof HostBookingsIndexRoute
}

const HostBookingsRouteChildren: HostBookingsRouteChildren = {
  HostBookingsBookingIdRoute: HostBookingsBookingIdRoute,
  HostBookingsIndexRoute: HostBookingsIndexRoute,
}

const HostBookingsRouteWithChildren = HostBookingsRoute._addFileChildren(
  HostBookingsRouteChildren,
)

interface HostExperiencesRouteChildren {
  HostExperiencesExperienceIdRoute: typeof HostExperiencesExperienceIdRoute
  HostExperiencesNewRoute: typeof HostExperiencesNewRoute
  HostExperiencesIndexRoute: typeof HostExperiencesIndexRoute
}

const HostExperiencesRouteChildren: HostExperiencesRouteChildren = {
  HostExperiencesExperienceIdRoute: HostExperiencesExperienceIdRoute,
  HostExperiencesNewRoute: HostExperiencesNewRoute,
  HostExperiencesIndexRoute: HostExperiencesIndexRoute,
}

const HostExperiencesRouteWithChildren = HostExperiencesRoute._addFileChildren(
  HostExperiencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CitiesRoute: CitiesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  HostsRoute: HostsRoute,
  JournalRoute: JournalRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AccountProfileRoute: AccountProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookingsBookingIdRoute: BookingsBookingIdRouteWithChildren,
  HostBookingsRoute: HostBookingsRouteWithChildren,
  HostDashboardRoute: HostDashboardRoute,
  HostExperiencesRoute: HostExperiencesRouteWithChildren,
  HostProfileRoute: HostProfileRoute,
  HostRevenueRoute: HostRevenueRoute,
  HostReviewsRoute: HostReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
