/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VipsIndexRouteImport } from './routes/vips.index'
import { Route as HomestaysIndexRouteImport } from './routes/homestays.index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VipsSlugRouteImport } from './routes/vips.$slug'
import { Route as VipListingsRouteImport } from './routes/vip.listings'
import { Route as VipDashboardRouteImport } from './routes/vip.dashboard'
import { Route as VipBookingsRouteImport } from './routes/vip.bookings'
import { Route as StaysBookingIdRouteImport } from './routes/stays.$bookingId'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as LegalPaymentPolicyRouteImport } from './routes/legal.payment-policy'
import { Route as LegalExperienceTermsRouteImport } from './routes/legal.experience-terms'
import { Route as HostReviewsRouteImport } from './routes/host.reviews'
import { Route as HostRevenueRouteImport } from './routes/host.revenue'
import { Route as HostProfileRouteImport } from './routes/host.profile'
import { Route as HostExperiencesRouteImport } from './routes/host.experiences'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as HostBookingsRouteImport } from './routes/host.bookings'
import { Route as HomestaysSlugRouteImport } from './routes/homestays.$slug'
import { Route as HomestayPropertiesRouteImport } from './routes/homestay.properties'
import { Route as HomestayDashboardRouteImport } from './routes/homestay.dashboard'
import { Route as HomestayBookingsRouteImport } from './routes/homestay.bookings'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard.wishlist'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPastRouteImport } from './routes/dashboard.past'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardCartRouteImport } from './routes/dashboard.cart'
import { Route as DashboardCancelledRouteImport } from './routes/dashboard.cancelled'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminHomestayFeaturedRouteImport } from './routes/admin.homestay-featured'
import { Route as AdminHomepagePhotosRouteImport } from './routes/admin.homepage-photos'
import { Route as AdminHomepageEditRouteImport } from './routes/admin.homepage-edit'
import { Route as AccountVipApplyRouteImport } from './routes/account.vip-apply'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as VipsBrowseIndexRouteImport } from './routes/vips.browse.index'
import { Route as VipsSlugIndexRouteImport } from './routes/vips.$slug.index'
import { Route as VipMembersIndexRouteImport } from './routes/vip.members.index'
import { Route as VipListingsIndexRouteImport } from './routes/vip.listings.index'
import { Route as VipCustomRequestsIndexRouteImport } from './routes/vip.custom-requests.index'
import { Route as VipBookingsIndexRouteImport } from './routes/vip.bookings.index'
import { Route as MemberVipIndexRouteImport } from './routes/member.vip.index'
import { Route as HostExperiencesIndexRouteImport } from './routes/host.experiences.index'
import { Route as HostBookingsIndexRouteImport } from './routes/host.bookings.index'
import { Route as HomestaysBrowseIndexRouteImport } from './routes/homestays.browse.index'
import { Route as HomestaysSlugIndexRouteImport } from './routes/homestays.$slug.index'
import { Route as HomestayPropertiesIndexRouteImport } from './routes/homestay.properties.index'
import { Route as HomestayBookingsIndexRouteImport } from './routes/homestay.bookings.index'
import { Route as ExperiencesSlugIndexRouteImport } from './routes/experiences.$slug.index'
import { Route as DashboardCartIndexRouteImport } from './routes/dashboard.cart.index'
import { Route as BookingsBookingIdIndexRouteImport } from './routes/bookings.$bookingId.index'
import { Route as AdminVipIndexRouteImport } from './routes/admin.vip.index'
import { Route as AdminVipPackagesIndexRouteImport } from './routes/admin.vip-packages.index'
import { Route as AdminVipOwnersIndexRouteImport } from './routes/admin.vip-owners.index'
import { Route as AdminTrustIndexRouteImport } from './routes/admin.trust.index'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin.reviews.index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin.profile.index'
import { Route as AdminHostsIndexRouteImport } from './routes/admin.hosts.index'
import { Route as AdminHomestaysIndexRouteImport } from './routes/admin.homestays.index'
import { Route as AdminHomestayIndexRouteImport } from './routes/admin.homestay.index'
import { Route as AdminHomestayOwnersIndexRouteImport } from './routes/admin.homestay-owners.index'
import { Route as AdminExperiencesIndexRouteImport } from './routes/admin.experiences.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminActivityIndexRouteImport } from './routes/admin.activity.index'
import { Route as VipListingsNewRouteImport } from './routes/vip.listings.new'
import { Route as VipListingsPackageIdRouteImport } from './routes/vip.listings.$packageId'
import { Route as MemberVipPackagesRouteImport } from './routes/member.vip.packages'
import { Route as MemberVipCustomRequestRouteImport } from './routes/member.vip.custom-request'
import { Route as HostExperiencesNewRouteImport } from './routes/host.experiences.new'
import { Route as HostExperiencesExperienceIdRouteImport } from './routes/host.experiences.$experienceId'
import { Route as HostBookingsBookingIdRouteImport } from './routes/host.bookings.$bookingId'
import { Route as HomestaysSlugBookRouteImport } from './routes/homestays.$slug.book'
import { Route as HomestayPropertiesNewRouteImport } from './routes/homestay.properties.new'
import { Route as HomestayPropertiesHomestayIdRouteImport } from './routes/homestay.properties.$homestayId'
import { Route as ExperiencesSlugBookRouteImport } from './routes/experiences.$slug.book'
import { Route as BookingsBookingIdReviewRouteImport } from './routes/bookings.$bookingId.review'
import { Route as AdminVipRequestsRouteImport } from './routes/admin.vip.requests'
import { Route as AdminVipPendingBookingsRouteImport } from './routes/admin.vip.pending-bookings'
import { Route as AdminVipPackagesPackageIdRouteImport } from './routes/admin.vip-packages.$packageId'
import { Route as AdminProfileUsersRouteImport } from './routes/admin.profile.users'
import { Route as AdminProfileMyTeamRouteImport } from './routes/admin.profile.my-team'
import { Route as AdminProfileHomepagePhotosRouteImport } from './routes/admin.profile.homepage-photos'
import { Route as AdminHomestaysHomestayIdRouteImport } from './routes/admin.homestays.$homestayId'
import { Route as AdminHomestayRequestsRouteImport } from './routes/admin.homestay.requests'
import { Route as AdminHomestayPendingBookingsRouteImport } from './routes/admin.homestay.pending-bookings'
import { Route as AdminExperiencesRequestsRouteImport } from './routes/admin.experiences.requests'
import { Route as AdminExperiencesPendingBookingsRouteImport } from './routes/admin.experiences.pending-bookings'
import { Route as AdminExperiencesExperienceIdRouteImport } from './routes/admin.experiences.$experienceId'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin.bookings.$bookingId'
import { Route as AdminReviewsHomestaysIndexRouteImport } from './routes/admin.reviews.homestays.index'
import { Route as AdminReviewsExperiencesIndexRouteImport } from './routes/admin.reviews.experiences.index'
import { Route as DashboardCartCheckoutSlugRouteImport } from './routes/dashboard.cart.checkout.$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipsIndexRoute = VipsIndexRouteImport.update({
  id: '/vips/',
  path: '/vips/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestaysIndexRoute = HomestaysIndexRouteImport.update({
  id: '/homestays/',
  path: '/homestays/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperiencesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VipsSlugRoute = VipsSlugRouteImport.update({
  id: '/vips/$slug',
  path: '/vips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VipListingsRoute = VipListingsRouteImport.update({
  id: '/vip/listings',
  path: '/vip/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const VipDashboardRoute = VipDashboardRouteImport.update({
  id: '/vip/dashboard',
  path: '/vip/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VipBookingsRoute = VipBookingsRouteImport.update({
  id: '/vip/bookings',
  path: '/vip/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysBookingIdRoute = StaysBookingIdRouteImport.update({
  id: '/stays/$bookingId',
  path: '/stays/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPaymentPolicyRoute = LegalPaymentPolicyRouteImport.update({
  id: '/legal/payment-policy',
  path: '/legal/payment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalExperienceTermsRoute = LegalExperienceTermsRouteImport.update({
  id: '/legal/experience-terms',
  path: '/legal/experience-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HostReviewsRoute = HostReviewsRouteImport.update({
  id: '/host/reviews',
  path: '/host/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRevenueRoute = HostRevenueRouteImport.update({
  id: '/host/revenue',
  path: '/host/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const HostProfileRoute = HostProfileRouteImport.update({
  id: '/host/profile',
  path: '/host/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HostExperiencesRoute = HostExperiencesRouteImport.update({
  id: '/host/experiences',
  path: '/host/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostBookingsRoute = HostBookingsRouteImport.update({
  id: '/host/bookings',
  path: '/host/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestaysSlugRoute = HomestaysSlugRouteImport.update({
  id: '/homestays/$slug',
  path: '/homestays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayPropertiesRoute = HomestayPropertiesRouteImport.update({
  id: '/homestay/properties',
  path: '/homestay/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayDashboardRoute = HomestayDashboardRouteImport.update({
  id: '/homestay/dashboard',
  path: '/homestay/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayBookingsRoute = HomestayBookingsRouteImport.update({
  id: '/homestay/bookings',
  path: '/homestay/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPastRoute = DashboardPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartRoute = DashboardCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCancelledRoute = DashboardCancelledRouteImport.update({
  id: '/cancelled',
  path: '/cancelled',
  getParentRoute: () => DashboardRoute,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CitiesRoute,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomestayFeaturedRoute = AdminHomestayFeaturedRouteImport.update({
  id: '/homestay-featured',
  path: '/homestay-featured',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepagePhotosRoute = AdminHomepagePhotosRouteImport.update({
  id: '/homepage-photos',
  path: '/homepage-photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageEditRoute = AdminHomepageEditRouteImport.update({
  id: '/homepage-edit',
  path: '/homepage-edit',
  getParentRoute: () => AdminRoute,
} as any)
const AccountVipApplyRoute = AccountVipApplyRouteImport.update({
  id: '/account/vip-apply',
  path: '/account/vip-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VipsBrowseIndexRoute = VipsBrowseIndexRouteImport.update({
  id: '/vips/browse/',
  path: '/vips/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipsSlugIndexRoute = VipsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VipsSlugRoute,
} as any)
const VipMembersIndexRoute = VipMembersIndexRouteImport.update({
  id: '/vip/members/',
  path: '/vip/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipListingsIndexRoute = VipListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VipListingsRoute,
} as any)
const VipCustomRequestsIndexRoute = VipCustomRequestsIndexRouteImport.update({
  id: '/vip/custom-requests/',
  path: '/vip/custom-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipBookingsIndexRoute = VipBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VipBookingsRoute,
} as any)
const MemberVipIndexRoute = MemberVipIndexRouteImport.update({
  id: '/member/vip/',
  path: '/member/vip/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostExperiencesIndexRoute = HostExperiencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostExperiencesRoute,
} as any)
const HostBookingsIndexRoute = HostBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostBookingsRoute,
} as any)
const HomestaysBrowseIndexRoute = HomestaysBrowseIndexRouteImport.update({
  id: '/homestays/browse/',
  path: '/homestays/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestaysSlugIndexRoute = HomestaysSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomestaysSlugRoute,
} as any)
const HomestayPropertiesIndexRoute = HomestayPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomestayPropertiesRoute,
} as any)
const HomestayBookingsIndexRoute = HomestayBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomestayBookingsRoute,
} as any)
const ExperiencesSlugIndexRoute = ExperiencesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperiencesSlugRoute,
} as any)
const DashboardCartIndexRoute = DashboardCartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCartRoute,
} as any)
const BookingsBookingIdIndexRoute = BookingsBookingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)
const AdminVipIndexRoute = AdminVipIndexRouteImport.update({
  id: '/vip/',
  path: '/vip/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVipPackagesIndexRoute = AdminVipPackagesIndexRouteImport.update({
  id: '/vip-packages/',
  path: '/vip-packages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVipOwnersIndexRoute = AdminVipOwnersIndexRouteImport.update({
  id: '/vip-owners/',
  path: '/vip-owners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrustIndexRoute = AdminTrustIndexRouteImport.update({
  id: '/trust/',
  path: '/trust/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProfileRoute,
} as any)
const AdminHostsIndexRoute = AdminHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomestaysIndexRoute = AdminHomestaysIndexRouteImport.update({
  id: '/homestays/',
  path: '/homestays/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomestayIndexRoute = AdminHomestayIndexRouteImport.update({
  id: '/homestay/',
  path: '/homestay/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomestayOwnersIndexRoute =
  AdminHomestayOwnersIndexRouteImport.update({
    id: '/homestay-owners/',
    path: '/homestay-owners/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExperiencesIndexRoute = AdminExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityIndexRoute = AdminActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AdminRoute,
} as any)
const VipListingsNewRoute = VipListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VipListingsRoute,
} as any)
const VipListingsPackageIdRoute = VipListingsPackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => VipListingsRoute,
} as any)
const MemberVipPackagesRoute = MemberVipPackagesRouteImport.update({
  id: '/member/vip/packages',
  path: '/member/vip/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberVipCustomRequestRoute = MemberVipCustomRequestRouteImport.update({
  id: '/member/vip/custom-request',
  path: '/member/vip/custom-request',
  getParentRoute: () => rootRouteImport,
} as any)
const HostExperiencesNewRoute = HostExperiencesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostExperiencesRoute,
} as any)
const HostExperiencesExperienceIdRoute =
  HostExperiencesExperienceIdRouteImport.update({
    id: '/$experienceId',
    path: '/$experienceId',
    getParentRoute: () => HostExperiencesRoute,
  } as any)
const HostBookingsBookingIdRoute = HostBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => HostBookingsRoute,
} as any)
const HomestaysSlugBookRoute = HomestaysSlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => HomestaysSlugRoute,
} as any)
const HomestayPropertiesNewRoute = HomestayPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HomestayPropertiesRoute,
} as any)
const HomestayPropertiesHomestayIdRoute =
  HomestayPropertiesHomestayIdRouteImport.update({
    id: '/$homestayId',
    path: '/$homestayId',
    getParentRoute: () => HomestayPropertiesRoute,
  } as any)
const ExperiencesSlugBookRoute = ExperiencesSlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ExperiencesSlugRoute,
} as any)
const BookingsBookingIdReviewRoute = BookingsBookingIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)
const AdminVipRequestsRoute = AdminVipRequestsRouteImport.update({
  id: '/vip/requests',
  path: '/vip/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVipPendingBookingsRoute = AdminVipPendingBookingsRouteImport.update({
  id: '/vip/pending-bookings',
  path: '/vip/pending-bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVipPackagesPackageIdRoute =
  AdminVipPackagesPackageIdRouteImport.update({
    id: '/vip-packages/$packageId',
    path: '/vip-packages/$packageId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProfileUsersRoute = AdminProfileUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminProfileRoute,
} as any)
const AdminProfileMyTeamRoute = AdminProfileMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AdminProfileRoute,
} as any)
const AdminProfileHomepagePhotosRoute =
  AdminProfileHomepagePhotosRouteImport.update({
    id: '/homepage-photos',
    path: '/homepage-photos',
    getParentRoute: () => AdminProfileRoute,
  } as any)
const AdminHomestaysHomestayIdRoute =
  AdminHomestaysHomestayIdRouteImport.update({
    id: '/homestays/$homestayId',
    path: '/homestays/$homestayId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminHomestayRequestsRoute = AdminHomestayRequestsRouteImport.update({
  id: '/homestay/requests',
  path: '/homestay/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomestayPendingBookingsRoute =
  AdminHomestayPendingBookingsRouteImport.update({
    id: '/homestay/pending-bookings',
    path: '/homestay/pending-bookings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExperiencesRequestsRoute =
  AdminExperiencesRequestsRouteImport.update({
    id: '/experiences/requests',
    path: '/experiences/requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExperiencesPendingBookingsRoute =
  AdminExperiencesPendingBookingsRouteImport.update({
    id: '/experiences/pending-bookings',
    path: '/experiences/pending-bookings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExperiencesExperienceIdRoute =
  AdminExperiencesExperienceIdRouteImport.update({
    id: '/experiences/$experienceId',
    path: '/experiences/$experienceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsHomestaysIndexRoute =
  AdminReviewsHomestaysIndexRouteImport.update({
    id: '/reviews/homestays/',
    path: '/reviews/homestays/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminReviewsExperiencesIndexRoute =
  AdminReviewsExperiencesIndexRouteImport.update({
    id: '/reviews/experiences/',
    path: '/reviews/experiences/',
    getParentRoute: () => AdminRoute,
  } as any)
const DashboardCartCheckoutSlugRoute =
  DashboardCartCheckoutSlugRouteImport.update({
    id: '/checkout/$slug',
    path: '/checkout/$slug',
    getParentRoute: () => DashboardCartRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/vip-apply': typeof AccountVipApplyRoute
  '/admin/homepage-edit': typeof AdminHomepageEditRoute
  '/admin/homepage-photos': typeof AdminHomepagePhotosRoute
  '/admin/homestay-featured': typeof AdminHomestayFeaturedRoute
  '/admin/profile': typeof AdminProfileRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/cities/$slug': typeof CitiesSlugRoute
  '/dashboard/cancelled': typeof DashboardCancelledRoute
  '/dashboard/cart': typeof DashboardCartRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/past': typeof DashboardPastRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/homestay/bookings': typeof HomestayBookingsRouteWithChildren
  '/homestay/dashboard': typeof HomestayDashboardRoute
  '/homestay/properties': typeof HomestayPropertiesRouteWithChildren
  '/homestays/$slug': typeof HomestaysSlugRouteWithChildren
  '/host/bookings': typeof HostBookingsRouteWithChildren
  '/host/dashboard': typeof HostDashboardRoute
  '/host/experiences': typeof HostExperiencesRouteWithChildren
  '/host/profile': typeof HostProfileRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/legal/experience-terms': typeof LegalExperienceTermsRoute
  '/legal/payment-policy': typeof LegalPaymentPolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/stays/$bookingId': typeof StaysBookingIdRoute
  '/vip/bookings': typeof VipBookingsRouteWithChildren
  '/vip/dashboard': typeof VipDashboardRoute
  '/vip/listings': typeof VipListingsRouteWithChildren
  '/vips/$slug': typeof VipsSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/homestays/': typeof HomestaysIndexRoute
  '/vips/': typeof VipsIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/experiences/$experienceId': typeof AdminExperiencesExperienceIdRoute
  '/admin/experiences/pending-bookings': typeof AdminExperiencesPendingBookingsRoute
  '/admin/experiences/requests': typeof AdminExperiencesRequestsRoute
  '/admin/homestay/pending-bookings': typeof AdminHomestayPendingBookingsRoute
  '/admin/homestay/requests': typeof AdminHomestayRequestsRoute
  '/admin/homestays/$homestayId': typeof AdminHomestaysHomestayIdRoute
  '/admin/profile/homepage-photos': typeof AdminProfileHomepagePhotosRoute
  '/admin/profile/my-team': typeof AdminProfileMyTeamRoute
  '/admin/profile/users': typeof AdminProfileUsersRoute
  '/admin/vip-packages/$packageId': typeof AdminVipPackagesPackageIdRoute
  '/admin/vip/pending-bookings': typeof AdminVipPendingBookingsRoute
  '/admin/vip/requests': typeof AdminVipRequestsRoute
  '/bookings/$bookingId/review': typeof BookingsBookingIdReviewRoute
  '/experiences/$slug/book': typeof ExperiencesSlugBookRoute
  '/homestay/properties/$homestayId': typeof HomestayPropertiesHomestayIdRoute
  '/homestay/properties/new': typeof HomestayPropertiesNewRoute
  '/homestays/$slug/book': typeof HomestaysSlugBookRoute
  '/host/bookings/$bookingId': typeof HostBookingsBookingIdRoute
  '/host/experiences/$experienceId': typeof HostExperiencesExperienceIdRoute
  '/host/experiences/new': typeof HostExperiencesNewRoute
  '/member/vip/custom-request': typeof MemberVipCustomRequestRoute
  '/member/vip/packages': typeof MemberVipPackagesRoute
  '/vip/listings/$packageId': typeof VipListingsPackageIdRoute
  '/vip/listings/new': typeof VipListingsNewRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/homestay-owners/': typeof AdminHomestayOwnersIndexRoute
  '/admin/homestay/': typeof AdminHomestayIndexRoute
  '/admin/homestays/': typeof AdminHomestaysIndexRoute
  '/admin/hosts/': typeof AdminHostsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/trust/': typeof AdminTrustIndexRoute
  '/admin/vip-owners/': typeof AdminVipOwnersIndexRoute
  '/admin/vip-packages/': typeof AdminVipPackagesIndexRoute
  '/admin/vip/': typeof AdminVipIndexRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/dashboard/cart/': typeof DashboardCartIndexRoute
  '/experiences/$slug/': typeof ExperiencesSlugIndexRoute
  '/homestay/bookings/': typeof HomestayBookingsIndexRoute
  '/homestay/properties/': typeof HomestayPropertiesIndexRoute
  '/homestays/$slug/': typeof HomestaysSlugIndexRoute
  '/homestays/browse/': typeof HomestaysBrowseIndexRoute
  '/host/bookings/': typeof HostBookingsIndexRoute
  '/host/experiences/': typeof HostExperiencesIndexRoute
  '/member/vip/': typeof MemberVipIndexRoute
  '/vip/bookings/': typeof VipBookingsIndexRoute
  '/vip/custom-requests/': typeof VipCustomRequestsIndexRoute
  '/vip/listings/': typeof VipListingsIndexRoute
  '/vip/members/': typeof VipMembersIndexRoute
  '/vips/$slug/': typeof VipsSlugIndexRoute
  '/vips/browse/': typeof VipsBrowseIndexRoute
  '/dashboard/cart/checkout/$slug': typeof DashboardCartCheckoutSlugRoute
  '/admin/reviews/experiences/': typeof AdminReviewsExperiencesIndexRoute
  '/admin/reviews/homestays/': typeof AdminReviewsHomestaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/vip-apply': typeof AccountVipApplyRoute
  '/admin/homepage-edit': typeof AdminHomepageEditRoute
  '/admin/homepage-photos': typeof AdminHomepagePhotosRoute
  '/admin/homestay-featured': typeof AdminHomestayFeaturedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/dashboard/cancelled': typeof DashboardCancelledRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/past': typeof DashboardPastRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/homestay/dashboard': typeof HomestayDashboardRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/profile': typeof HostProfileRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/legal/experience-terms': typeof LegalExperienceTermsRoute
  '/legal/payment-policy': typeof LegalPaymentPolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/stays/$bookingId': typeof StaysBookingIdRoute
  '/vip/dashboard': typeof VipDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/homestays': typeof HomestaysIndexRoute
  '/vips': typeof VipsIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/experiences/$experienceId': typeof AdminExperiencesExperienceIdRoute
  '/admin/experiences/pending-bookings': typeof AdminExperiencesPendingBookingsRoute
  '/admin/experiences/requests': typeof AdminExperiencesRequestsRoute
  '/admin/homestay/pending-bookings': typeof AdminHomestayPendingBookingsRoute
  '/admin/homestay/requests': typeof AdminHomestayRequestsRoute
  '/admin/homestays/$homestayId': typeof AdminHomestaysHomestayIdRoute
  '/admin/profile/homepage-photos': typeof AdminProfileHomepagePhotosRoute
  '/admin/profile/my-team': typeof AdminProfileMyTeamRoute
  '/admin/profile/users': typeof AdminProfileUsersRoute
  '/admin/vip-packages/$packageId': typeof AdminVipPackagesPackageIdRoute
  '/admin/vip/pending-bookings': typeof AdminVipPendingBookingsRoute
  '/admin/vip/requests': typeof AdminVipRequestsRoute
  '/bookings/$bookingId/review': typeof BookingsBookingIdReviewRoute
  '/experiences/$slug/book': typeof ExperiencesSlugBookRoute
  '/homestay/properties/$homestayId': typeof HomestayPropertiesHomestayIdRoute
  '/homestay/properties/new': typeof HomestayPropertiesNewRoute
  '/homestays/$slug/book': typeof HomestaysSlugBookRoute
  '/host/bookings/$bookingId': typeof HostBookingsBookingIdRoute
  '/host/experiences/$experienceId': typeof HostExperiencesExperienceIdRoute
  '/host/experiences/new': typeof HostExperiencesNewRoute
  '/member/vip/custom-request': typeof MemberVipCustomRequestRoute
  '/member/vip/packages': typeof MemberVipPackagesRoute
  '/vip/listings/$packageId': typeof VipListingsPackageIdRoute
  '/vip/listings/new': typeof VipListingsNewRoute
  '/admin/activity': typeof AdminActivityIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/experiences': typeof AdminExperiencesIndexRoute
  '/admin/homestay-owners': typeof AdminHomestayOwnersIndexRoute
  '/admin/homestay': typeof AdminHomestayIndexRoute
  '/admin/homestays': typeof AdminHomestaysIndexRoute
  '/admin/hosts': typeof AdminHostsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/trust': typeof AdminTrustIndexRoute
  '/admin/vip-owners': typeof AdminVipOwnersIndexRoute
  '/admin/vip-packages': typeof AdminVipPackagesIndexRoute
  '/admin/vip': typeof AdminVipIndexRoute
  '/bookings/$bookingId': typeof BookingsBookingIdIndexRoute
  '/dashboard/cart': typeof DashboardCartIndexRoute
  '/experiences/$slug': typeof ExperiencesSlugIndexRoute
  '/homestay/bookings': typeof HomestayBookingsIndexRoute
  '/homestay/properties': typeof HomestayPropertiesIndexRoute
  '/homestays/$slug': typeof HomestaysSlugIndexRoute
  '/homestays/browse': typeof HomestaysBrowseIndexRoute
  '/host/bookings': typeof HostBookingsIndexRoute
  '/host/experiences': typeof HostExperiencesIndexRoute
  '/member/vip': typeof MemberVipIndexRoute
  '/vip/bookings': typeof VipBookingsIndexRoute
  '/vip/custom-requests': typeof VipCustomRequestsIndexRoute
  '/vip/listings': typeof VipListingsIndexRoute
  '/vip/members': typeof VipMembersIndexRoute
  '/vips/$slug': typeof VipsSlugIndexRoute
  '/vips/browse': typeof VipsBrowseIndexRoute
  '/dashboard/cart/checkout/$slug': typeof DashboardCartCheckoutSlugRoute
  '/admin/reviews/experiences': typeof AdminReviewsExperiencesIndexRoute
  '/admin/reviews/homestays': typeof AdminReviewsHomestaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/vip-apply': typeof AccountVipApplyRoute
  '/admin/homepage-edit': typeof AdminHomepageEditRoute
  '/admin/homepage-photos': typeof AdminHomepagePhotosRoute
  '/admin/homestay-featured': typeof AdminHomestayFeaturedRoute
  '/admin/profile': typeof AdminProfileRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/cities/$slug': typeof CitiesSlugRoute
  '/dashboard/cancelled': typeof DashboardCancelledRoute
  '/dashboard/cart': typeof DashboardCartRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/past': typeof DashboardPastRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/homestay/bookings': typeof HomestayBookingsRouteWithChildren
  '/homestay/dashboard': typeof HomestayDashboardRoute
  '/homestay/properties': typeof HomestayPropertiesRouteWithChildren
  '/homestays/$slug': typeof HomestaysSlugRouteWithChildren
  '/host/bookings': typeof HostBookingsRouteWithChildren
  '/host/dashboard': typeof HostDashboardRoute
  '/host/experiences': typeof HostExperiencesRouteWithChildren
  '/host/profile': typeof HostProfileRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/legal/experience-terms': typeof LegalExperienceTermsRoute
  '/legal/payment-policy': typeof LegalPaymentPolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/stays/$bookingId': typeof StaysBookingIdRoute
  '/vip/bookings': typeof VipBookingsRouteWithChildren
  '/vip/dashboard': typeof VipDashboardRoute
  '/vip/listings': typeof VipListingsRouteWithChildren
  '/vips/$slug': typeof VipsSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/homestays/': typeof HomestaysIndexRoute
  '/vips/': typeof VipsIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/experiences/$experienceId': typeof AdminExperiencesExperienceIdRoute
  '/admin/experiences/pending-bookings': typeof AdminExperiencesPendingBookingsRoute
  '/admin/experiences/requests': typeof AdminExperiencesRequestsRoute
  '/admin/homestay/pending-bookings': typeof AdminHomestayPendingBookingsRoute
  '/admin/homestay/requests': typeof AdminHomestayRequestsRoute
  '/admin/homestays/$homestayId': typeof AdminHomestaysHomestayIdRoute
  '/admin/profile/homepage-photos': typeof AdminProfileHomepagePhotosRoute
  '/admin/profile/my-team': typeof AdminProfileMyTeamRoute
  '/admin/profile/users': typeof AdminProfileUsersRoute
  '/admin/vip-packages/$packageId': typeof AdminVipPackagesPackageIdRoute
  '/admin/vip/pending-bookings': typeof AdminVipPendingBookingsRoute
  '/admin/vip/requests': typeof AdminVipRequestsRoute
  '/bookings/$bookingId/review': typeof BookingsBookingIdReviewRoute
  '/experiences/$slug/book': typeof ExperiencesSlugBookRoute
  '/homestay/properties/$homestayId': typeof HomestayPropertiesHomestayIdRoute
  '/homestay/properties/new': typeof HomestayPropertiesNewRoute
  '/homestays/$slug/book': typeof HomestaysSlugBookRoute
  '/host/bookings/$bookingId': typeof HostBookingsBookingIdRoute
  '/host/experiences/$experienceId': typeof HostExperiencesExperienceIdRoute
  '/host/experiences/new': typeof HostExperiencesNewRoute
  '/member/vip/custom-request': typeof MemberVipCustomRequestRoute
  '/member/vip/packages': typeof MemberVipPackagesRoute
  '/vip/listings/$packageId': typeof VipListingsPackageIdRoute
  '/vip/listings/new': typeof VipListingsNewRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/homestay-owners/': typeof AdminHomestayOwnersIndexRoute
  '/admin/homestay/': typeof AdminHomestayIndexRoute
  '/admin/homestays/': typeof AdminHomestaysIndexRoute
  '/admin/hosts/': typeof AdminHostsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/trust/': typeof AdminTrustIndexRoute
  '/admin/vip-owners/': typeof AdminVipOwnersIndexRoute
  '/admin/vip-packages/': typeof AdminVipPackagesIndexRoute
  '/admin/vip/': typeof AdminVipIndexRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/dashboard/cart/': typeof DashboardCartIndexRoute
  '/experiences/$slug/': typeof ExperiencesSlugIndexRoute
  '/homestay/bookings/': typeof HomestayBookingsIndexRoute
  '/homestay/properties/': typeof HomestayPropertiesIndexRoute
  '/homestays/$slug/': typeof HomestaysSlugIndexRoute
  '/homestays/browse/': typeof HomestaysBrowseIndexRoute
  '/host/bookings/': typeof HostBookingsIndexRoute
  '/host/experiences/': typeof HostExperiencesIndexRoute
  '/member/vip/': typeof MemberVipIndexRoute
  '/vip/bookings/': typeof VipBookingsIndexRoute
  '/vip/custom-requests/': typeof VipCustomRequestsIndexRoute
  '/vip/listings/': typeof VipListingsIndexRoute
  '/vip/members/': typeof VipMembersIndexRoute
  '/vips/$slug/': typeof VipsSlugIndexRoute
  '/vips/browse/': typeof VipsBrowseIndexRoute
  '/dashboard/cart/checkout/$slug': typeof DashboardCartCheckoutSlugRoute
  '/admin/reviews/experiences/': typeof AdminReviewsExperiencesIndexRoute
  '/admin/reviews/homestays/': typeof AdminReviewsHomestaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cities'
    | '/contact'
    | '/dashboard'
    | '/experiences'
    | '/forgot-password'
    | '/journal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/account/profile'
    | '/account/vip-apply'
    | '/admin/homepage-edit'
    | '/admin/homepage-photos'
    | '/admin/homestay-featured'
    | '/admin/profile'
    | '/auth/callback'
    | '/bookings/$bookingId'
    | '/cities/$slug'
    | '/dashboard/cancelled'
    | '/dashboard/cart'
    | '/dashboard/history'
    | '/dashboard/past'
    | '/dashboard/profile'
    | '/dashboard/wishlist'
    | '/experiences/$slug'
    | '/homestay/bookings'
    | '/homestay/dashboard'
    | '/homestay/properties'
    | '/homestays/$slug'
    | '/host/bookings'
    | '/host/dashboard'
    | '/host/experiences'
    | '/host/profile'
    | '/host/revenue'
    | '/host/reviews'
    | '/legal/experience-terms'
    | '/legal/payment-policy'
    | '/legal/privacy-policy'
    | '/stays/$bookingId'
    | '/vip/bookings'
    | '/vip/dashboard'
    | '/vip/listings'
    | '/vips/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/experiences/'
    | '/homestays/'
    | '/vips/'
    | '/admin/bookings/$bookingId'
    | '/admin/experiences/$experienceId'
    | '/admin/experiences/pending-bookings'
    | '/admin/experiences/requests'
    | '/admin/homestay/pending-bookings'
    | '/admin/homestay/requests'
    | '/admin/homestays/$homestayId'
    | '/admin/profile/homepage-photos'
    | '/admin/profile/my-team'
    | '/admin/profile/users'
    | '/admin/vip-packages/$packageId'
    | '/admin/vip/pending-bookings'
    | '/admin/vip/requests'
    | '/bookings/$bookingId/review'
    | '/experiences/$slug/book'
    | '/homestay/properties/$homestayId'
    | '/homestay/properties/new'
    | '/homestays/$slug/book'
    | '/host/bookings/$bookingId'
    | '/host/experiences/$experienceId'
    | '/host/experiences/new'
    | '/member/vip/custom-request'
    | '/member/vip/packages'
    | '/vip/listings/$packageId'
    | '/vip/listings/new'
    | '/admin/activity/'
    | '/admin/bookings/'
    | '/admin/experiences/'
    | '/admin/homestay-owners/'
    | '/admin/homestay/'
    | '/admin/homestays/'
    | '/admin/hosts/'
    | '/admin/profile/'
    | '/admin/reviews/'
    | '/admin/trust/'
    | '/admin/vip-owners/'
    | '/admin/vip-packages/'
    | '/admin/vip/'
    | '/bookings/$bookingId/'
    | '/dashboard/cart/'
    | '/experiences/$slug/'
    | '/homestay/bookings/'
    | '/homestay/properties/'
    | '/homestays/$slug/'
    | '/homestays/browse/'
    | '/host/bookings/'
    | '/host/experiences/'
    | '/member/vip/'
    | '/vip/bookings/'
    | '/vip/custom-requests/'
    | '/vip/listings/'
    | '/vip/members/'
    | '/vips/$slug/'
    | '/vips/browse/'
    | '/dashboard/cart/checkout/$slug'
    | '/admin/reviews/experiences/'
    | '/admin/reviews/homestays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cities'
    | '/contact'
    | '/forgot-password'
    | '/journal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/account/profile'
    | '/account/vip-apply'
    | '/admin/homepage-edit'
    | '/admin/homepage-photos'
    | '/admin/homestay-featured'
    | '/auth/callback'
    | '/cities/$slug'
    | '/dashboard/cancelled'
    | '/dashboard/history'
    | '/dashboard/past'
    | '/dashboard/profile'
    | '/dashboard/wishlist'
    | '/homestay/dashboard'
    | '/host/dashboard'
    | '/host/profile'
    | '/host/revenue'
    | '/host/reviews'
    | '/legal/experience-terms'
    | '/legal/payment-policy'
    | '/legal/privacy-policy'
    | '/stays/$bookingId'
    | '/vip/dashboard'
    | '/admin'
    | '/dashboard'
    | '/experiences'
    | '/homestays'
    | '/vips'
    | '/admin/bookings/$bookingId'
    | '/admin/experiences/$experienceId'
    | '/admin/experiences/pending-bookings'
    | '/admin/experiences/requests'
    | '/admin/homestay/pending-bookings'
    | '/admin/homestay/requests'
    | '/admin/homestays/$homestayId'
    | '/admin/profile/homepage-photos'
    | '/admin/profile/my-team'
    | '/admin/profile/users'
    | '/admin/vip-packages/$packageId'
    | '/admin/vip/pending-bookings'
    | '/admin/vip/requests'
    | '/bookings/$bookingId/review'
    | '/experiences/$slug/book'
    | '/homestay/properties/$homestayId'
    | '/homestay/properties/new'
    | '/homestays/$slug/book'
    | '/host/bookings/$bookingId'
    | '/host/experiences/$experienceId'
    | '/host/experiences/new'
    | '/member/vip/custom-request'
    | '/member/vip/packages'
    | '/vip/listings/$packageId'
    | '/vip/listings/new'
    | '/admin/activity'
    | '/admin/bookings'
    | '/admin/experiences'
    | '/admin/homestay-owners'
    | '/admin/homestay'
    | '/admin/homestays'
    | '/admin/hosts'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/trust'
    | '/admin/vip-owners'
    | '/admin/vip-packages'
    | '/admin/vip'
    | '/bookings/$bookingId'
    | '/dashboard/cart'
    | '/experiences/$slug'
    | '/homestay/bookings'
    | '/homestay/properties'
    | '/homestays/$slug'
    | '/homestays/browse'
    | '/host/bookings'
    | '/host/experiences'
    | '/member/vip'
    | '/vip/bookings'
    | '/vip/custom-requests'
    | '/vip/listings'
    | '/vip/members'
    | '/vips/$slug'
    | '/vips/browse'
    | '/dashboard/cart/checkout/$slug'
    | '/admin/reviews/experiences'
    | '/admin/reviews/homestays'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cities'
    | '/contact'
    | '/dashboard'
    | '/experiences'
    | '/forgot-password'
    | '/journal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/account/profile'
    | '/account/vip-apply'
    | '/admin/homepage-edit'
    | '/admin/homepage-photos'
    | '/admin/homestay-featured'
    | '/admin/profile'
    | '/auth/callback'
    | '/bookings/$bookingId'
    | '/cities/$slug'
    | '/dashboard/cancelled'
    | '/dashboard/cart'
    | '/dashboard/history'
    | '/dashboard/past'
    | '/dashboard/profile'
    | '/dashboard/wishlist'
    | '/experiences/$slug'
    | '/homestay/bookings'
    | '/homestay/dashboard'
    | '/homestay/properties'
    | '/homestays/$slug'
    | '/host/bookings'
    | '/host/dashboard'
    | '/host/experiences'
    | '/host/profile'
    | '/host/revenue'
    | '/host/reviews'
    | '/legal/experience-terms'
    | '/legal/payment-policy'
    | '/legal/privacy-policy'
    | '/stays/$bookingId'
    | '/vip/bookings'
    | '/vip/dashboard'
    | '/vip/listings'
    | '/vips/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/experiences/'
    | '/homestays/'
    | '/vips/'
    | '/admin/bookings/$bookingId'
    | '/admin/experiences/$experienceId'
    | '/admin/experiences/pending-bookings'
    | '/admin/experiences/requests'
    | '/admin/homestay/pending-bookings'
    | '/admin/homestay/requests'
    | '/admin/homestays/$homestayId'
    | '/admin/profile/homepage-photos'
    | '/admin/profile/my-team'
    | '/admin/profile/users'
    | '/admin/vip-packages/$packageId'
    | '/admin/vip/pending-bookings'
    | '/admin/vip/requests'
    | '/bookings/$bookingId/review'
    | '/experiences/$slug/book'
    | '/homestay/properties/$homestayId'
    | '/homestay/properties/new'
    | '/homestays/$slug/book'
    | '/host/bookings/$bookingId'
    | '/host/experiences/$experienceId'
    | '/host/experiences/new'
    | '/member/vip/custom-request'
    | '/member/vip/packages'
    | '/vip/listings/$packageId'
    | '/vip/listings/new'
    | '/admin/activity/'
    | '/admin/bookings/'
    | '/admin/experiences/'
    | '/admin/homestay-owners/'
    | '/admin/homestay/'
    | '/admin/homestays/'
    | '/admin/hosts/'
    | '/admin/profile/'
    | '/admin/reviews/'
    | '/admin/trust/'
    | '/admin/vip-owners/'
    | '/admin/vip-packages/'
    | '/admin/vip/'
    | '/bookings/$bookingId/'
    | '/dashboard/cart/'
    | '/experiences/$slug/'
    | '/homestay/bookings/'
    | '/homestay/properties/'
    | '/homestays/$slug/'
    | '/homestays/browse/'
    | '/host/bookings/'
    | '/host/experiences/'
    | '/member/vip/'
    | '/vip/bookings/'
    | '/vip/custom-requests/'
    | '/vip/listings/'
    | '/vip/members/'
    | '/vips/$slug/'
    | '/vips/browse/'
    | '/dashboard/cart/checkout/$slug'
    | '/admin/reviews/experiences/'
    | '/admin/reviews/homestays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitiesRoute: typeof CitiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JournalRoute: typeof JournalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountVipApplyRoute: typeof AccountVipApplyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRouteWithChildren
  HomestayBookingsRoute: typeof HomestayBookingsRouteWithChildren
  HomestayDashboardRoute: typeof HomestayDashboardRoute
  HomestayPropertiesRoute: typeof HomestayPropertiesRouteWithChildren
  HomestaysSlugRoute: typeof HomestaysSlugRouteWithChildren
  HostBookingsRoute: typeof HostBookingsRouteWithChildren
  HostDashboardRoute: typeof HostDashboardRoute
  HostExperiencesRoute: typeof HostExperiencesRouteWithChildren
  HostProfileRoute: typeof HostProfileRoute
  HostRevenueRoute: typeof HostRevenueRoute
  HostReviewsRoute: typeof HostReviewsRoute
  LegalExperienceTermsRoute: typeof LegalExperienceTermsRoute
  LegalPaymentPolicyRoute: typeof LegalPaymentPolicyRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  StaysBookingIdRoute: typeof StaysBookingIdRoute
  VipBookingsRoute: typeof VipBookingsRouteWithChildren
  VipDashboardRoute: typeof VipDashboardRoute
  VipListingsRoute: typeof VipListingsRouteWithChildren
  VipsSlugRoute: typeof VipsSlugRouteWithChildren
  HomestaysIndexRoute: typeof HomestaysIndexRoute
  VipsIndexRoute: typeof VipsIndexRoute
  MemberVipCustomRequestRoute: typeof MemberVipCustomRequestRoute
  MemberVipPackagesRoute: typeof MemberVipPackagesRoute
  HomestaysBrowseIndexRoute: typeof HomestaysBrowseIndexRoute
  MemberVipIndexRoute: typeof MemberVipIndexRoute
  VipCustomRequestsIndexRoute: typeof VipCustomRequestsIndexRoute
  VipMembersIndexRoute: typeof VipMembersIndexRoute
  VipsBrowseIndexRoute: typeof VipsBrowseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vips/': {
      id: '/vips/'
      path: '/vips'
      fullPath: '/vips/'
      preLoaderRoute: typeof VipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestays/': {
      id: '/homestays/'
      path: '/homestays'
      fullPath: '/homestays/'
      preLoaderRoute: typeof HomestaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vips/$slug': {
      id: '/vips/$slug'
      path: '/vips/$slug'
      fullPath: '/vips/$slug'
      preLoaderRoute: typeof VipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/listings': {
      id: '/vip/listings'
      path: '/vip/listings'
      fullPath: '/vip/listings'
      preLoaderRoute: typeof VipListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/dashboard': {
      id: '/vip/dashboard'
      path: '/vip/dashboard'
      fullPath: '/vip/dashboard'
      preLoaderRoute: typeof VipDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/bookings': {
      id: '/vip/bookings'
      path: '/vip/bookings'
      fullPath: '/vip/bookings'
      preLoaderRoute: typeof VipBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$bookingId': {
      id: '/stays/$bookingId'
      path: '/stays/$bookingId'
      fullPath: '/stays/$bookingId'
      preLoaderRoute: typeof StaysBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/payment-policy': {
      id: '/legal/payment-policy'
      path: '/legal/payment-policy'
      fullPath: '/legal/payment-policy'
      preLoaderRoute: typeof LegalPaymentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/experience-terms': {
      id: '/legal/experience-terms'
      path: '/legal/experience-terms'
      fullPath: '/legal/experience-terms'
      preLoaderRoute: typeof LegalExperienceTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/reviews': {
      id: '/host/reviews'
      path: '/host/reviews'
      fullPath: '/host/reviews'
      preLoaderRoute: typeof HostReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/revenue': {
      id: '/host/revenue'
      path: '/host/revenue'
      fullPath: '/host/revenue'
      preLoaderRoute: typeof HostRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/profile': {
      id: '/host/profile'
      path: '/host/profile'
      fullPath: '/host/profile'
      preLoaderRoute: typeof HostProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/experiences': {
      id: '/host/experiences'
      path: '/host/experiences'
      fullPath: '/host/experiences'
      preLoaderRoute: typeof HostExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/bookings': {
      id: '/host/bookings'
      path: '/host/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof HostBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestays/$slug': {
      id: '/homestays/$slug'
      path: '/homestays/$slug'
      fullPath: '/homestays/$slug'
      preLoaderRoute: typeof HomestaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay/properties': {
      id: '/homestay/properties'
      path: '/homestay/properties'
      fullPath: '/homestay/properties'
      preLoaderRoute: typeof HomestayPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay/dashboard': {
      id: '/homestay/dashboard'
      path: '/homestay/dashboard'
      fullPath: '/homestay/dashboard'
      preLoaderRoute: typeof HomestayDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay/bookings': {
      id: '/homestay/bookings'
      path: '/homestay/bookings'
      fullPath: '/homestay/bookings'
      preLoaderRoute: typeof HomestayBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/past': {
      id: '/dashboard/past'
      path: '/past'
      fullPath: '/dashboard/past'
      preLoaderRoute: typeof DashboardPastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart': {
      id: '/dashboard/cart'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof DashboardCartRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cancelled': {
      id: '/dashboard/cancelled'
      path: '/cancelled'
      fullPath: '/dashboard/cancelled'
      preLoaderRoute: typeof DashboardCancelledRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homestay-featured': {
      id: '/admin/homestay-featured'
      path: '/homestay-featured'
      fullPath: '/admin/homestay-featured'
      preLoaderRoute: typeof AdminHomestayFeaturedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage-photos': {
      id: '/admin/homepage-photos'
      path: '/homepage-photos'
      fullPath: '/admin/homepage-photos'
      preLoaderRoute: typeof AdminHomepagePhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage-edit': {
      id: '/admin/homepage-edit'
      path: '/homepage-edit'
      fullPath: '/admin/homepage-edit'
      preLoaderRoute: typeof AdminHomepageEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/vip-apply': {
      id: '/account/vip-apply'
      path: '/account/vip-apply'
      fullPath: '/account/vip-apply'
      preLoaderRoute: typeof AccountVipApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vips/browse/': {
      id: '/vips/browse/'
      path: '/vips/browse'
      fullPath: '/vips/browse/'
      preLoaderRoute: typeof VipsBrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vips/$slug/': {
      id: '/vips/$slug/'
      path: '/'
      fullPath: '/vips/$slug/'
      preLoaderRoute: typeof VipsSlugIndexRouteImport
      parentRoute: typeof VipsSlugRoute
    }
    '/vip/members/': {
      id: '/vip/members/'
      path: '/vip/members'
      fullPath: '/vip/members/'
      preLoaderRoute: typeof VipMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/listings/': {
      id: '/vip/listings/'
      path: '/'
      fullPath: '/vip/listings/'
      preLoaderRoute: typeof VipListingsIndexRouteImport
      parentRoute: typeof VipListingsRoute
    }
    '/vip/custom-requests/': {
      id: '/vip/custom-requests/'
      path: '/vip/custom-requests'
      fullPath: '/vip/custom-requests/'
      preLoaderRoute: typeof VipCustomRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/bookings/': {
      id: '/vip/bookings/'
      path: '/'
      fullPath: '/vip/bookings/'
      preLoaderRoute: typeof VipBookingsIndexRouteImport
      parentRoute: typeof VipBookingsRoute
    }
    '/member/vip/': {
      id: '/member/vip/'
      path: '/member/vip'
      fullPath: '/member/vip/'
      preLoaderRoute: typeof MemberVipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/experiences/': {
      id: '/host/experiences/'
      path: '/'
      fullPath: '/host/experiences/'
      preLoaderRoute: typeof HostExperiencesIndexRouteImport
      parentRoute: typeof HostExperiencesRoute
    }
    '/host/bookings/': {
      id: '/host/bookings/'
      path: '/'
      fullPath: '/host/bookings/'
      preLoaderRoute: typeof HostBookingsIndexRouteImport
      parentRoute: typeof HostBookingsRoute
    }
    '/homestays/browse/': {
      id: '/homestays/browse/'
      path: '/homestays/browse'
      fullPath: '/homestays/browse/'
      preLoaderRoute: typeof HomestaysBrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestays/$slug/': {
      id: '/homestays/$slug/'
      path: '/'
      fullPath: '/homestays/$slug/'
      preLoaderRoute: typeof HomestaysSlugIndexRouteImport
      parentRoute: typeof HomestaysSlugRoute
    }
    '/homestay/properties/': {
      id: '/homestay/properties/'
      path: '/'
      fullPath: '/homestay/properties/'
      preLoaderRoute: typeof HomestayPropertiesIndexRouteImport
      parentRoute: typeof HomestayPropertiesRoute
    }
    '/homestay/bookings/': {
      id: '/homestay/bookings/'
      path: '/'
      fullPath: '/homestay/bookings/'
      preLoaderRoute: typeof HomestayBookingsIndexRouteImport
      parentRoute: typeof HomestayBookingsRoute
    }
    '/experiences/$slug/': {
      id: '/experiences/$slug/'
      path: '/'
      fullPath: '/experiences/$slug/'
      preLoaderRoute: typeof ExperiencesSlugIndexRouteImport
      parentRoute: typeof ExperiencesSlugRoute
    }
    '/dashboard/cart/': {
      id: '/dashboard/cart/'
      path: '/'
      fullPath: '/dashboard/cart/'
      preLoaderRoute: typeof DashboardCartIndexRouteImport
      parentRoute: typeof DashboardCartRoute
    }
    '/bookings/$bookingId/': {
      id: '/bookings/$bookingId/'
      path: '/'
      fullPath: '/bookings/$bookingId/'
      preLoaderRoute: typeof BookingsBookingIdIndexRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/admin/vip/': {
      id: '/admin/vip/'
      path: '/vip'
      fullPath: '/admin/vip/'
      preLoaderRoute: typeof AdminVipIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vip-packages/': {
      id: '/admin/vip-packages/'
      path: '/vip-packages'
      fullPath: '/admin/vip-packages/'
      preLoaderRoute: typeof AdminVipPackagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vip-owners/': {
      id: '/admin/vip-owners/'
      path: '/vip-owners'
      fullPath: '/admin/vip-owners/'
      preLoaderRoute: typeof AdminVipOwnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trust/': {
      id: '/admin/trust/'
      path: '/trust'
      fullPath: '/admin/trust/'
      preLoaderRoute: typeof AdminTrustIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminProfileRoute
    }
    '/admin/hosts/': {
      id: '/admin/hosts/'
      path: '/hosts'
      fullPath: '/admin/hosts/'
      preLoaderRoute: typeof AdminHostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homestays/': {
      id: '/admin/homestays/'
      path: '/homestays'
      fullPath: '/admin/homestays/'
      preLoaderRoute: typeof AdminHomestaysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homestay/': {
      id: '/admin/homestay/'
      path: '/homestay'
      fullPath: '/admin/homestay/'
      preLoaderRoute: typeof AdminHomestayIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homestay-owners/': {
      id: '/admin/homestay-owners/'
      path: '/homestay-owners'
      fullPath: '/admin/homestay-owners/'
      preLoaderRoute: typeof AdminHomestayOwnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/': {
      id: '/admin/experiences/'
      path: '/experiences'
      fullPath: '/admin/experiences/'
      preLoaderRoute: typeof AdminExperiencesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity/': {
      id: '/admin/activity/'
      path: '/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AdminActivityIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vip/listings/new': {
      id: '/vip/listings/new'
      path: '/new'
      fullPath: '/vip/listings/new'
      preLoaderRoute: typeof VipListingsNewRouteImport
      parentRoute: typeof VipListingsRoute
    }
    '/vip/listings/$packageId': {
      id: '/vip/listings/$packageId'
      path: '/$packageId'
      fullPath: '/vip/listings/$packageId'
      preLoaderRoute: typeof VipListingsPackageIdRouteImport
      parentRoute: typeof VipListingsRoute
    }
    '/member/vip/packages': {
      id: '/member/vip/packages'
      path: '/member/vip/packages'
      fullPath: '/member/vip/packages'
      preLoaderRoute: typeof MemberVipPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/vip/custom-request': {
      id: '/member/vip/custom-request'
      path: '/member/vip/custom-request'
      fullPath: '/member/vip/custom-request'
      preLoaderRoute: typeof MemberVipCustomRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/experiences/new': {
      id: '/host/experiences/new'
      path: '/new'
      fullPath: '/host/experiences/new'
      preLoaderRoute: typeof HostExperiencesNewRouteImport
      parentRoute: typeof HostExperiencesRoute
    }
    '/host/experiences/$experienceId': {
      id: '/host/experiences/$experienceId'
      path: '/$experienceId'
      fullPath: '/host/experiences/$experienceId'
      preLoaderRoute: typeof HostExperiencesExperienceIdRouteImport
      parentRoute: typeof HostExperiencesRoute
    }
    '/host/bookings/$bookingId': {
      id: '/host/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/host/bookings/$bookingId'
      preLoaderRoute: typeof HostBookingsBookingIdRouteImport
      parentRoute: typeof HostBookingsRoute
    }
    '/homestays/$slug/book': {
      id: '/homestays/$slug/book'
      path: '/book'
      fullPath: '/homestays/$slug/book'
      preLoaderRoute: typeof HomestaysSlugBookRouteImport
      parentRoute: typeof HomestaysSlugRoute
    }
    '/homestay/properties/new': {
      id: '/homestay/properties/new'
      path: '/new'
      fullPath: '/homestay/properties/new'
      preLoaderRoute: typeof HomestayPropertiesNewRouteImport
      parentRoute: typeof HomestayPropertiesRoute
    }
    '/homestay/properties/$homestayId': {
      id: '/homestay/properties/$homestayId'
      path: '/$homestayId'
      fullPath: '/homestay/properties/$homestayId'
      preLoaderRoute: typeof HomestayPropertiesHomestayIdRouteImport
      parentRoute: typeof HomestayPropertiesRoute
    }
    '/experiences/$slug/book': {
      id: '/experiences/$slug/book'
      path: '/book'
      fullPath: '/experiences/$slug/book'
      preLoaderRoute: typeof ExperiencesSlugBookRouteImport
      parentRoute: typeof ExperiencesSlugRoute
    }
    '/bookings/$bookingId/review': {
      id: '/bookings/$bookingId/review'
      path: '/review'
      fullPath: '/bookings/$bookingId/review'
      preLoaderRoute: typeof BookingsBookingIdReviewRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/admin/vip/requests': {
      id: '/admin/vip/requests'
      path: '/vip/requests'
      fullPath: '/admin/vip/requests'
      preLoaderRoute: typeof AdminVipRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vip/pending-bookings': {
      id: '/admin/vip/pending-bookings'
      path: '/vip/pending-bookings'
      fullPath: '/admin/vip/pending-bookings'
      preLoaderRoute: typeof AdminVipPendingBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vip-packages/$packageId': {
      id: '/admin/vip-packages/$packageId'
      path: '/vip-packages/$packageId'
      fullPath: '/admin/vip-packages/$packageId'
      preLoaderRoute: typeof AdminVipPackagesPackageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/users': {
      id: '/admin/profile/users'
      path: '/users'
      fullPath: '/admin/profile/users'
      preLoaderRoute: typeof AdminProfileUsersRouteImport
      parentRoute: typeof AdminProfileRoute
    }
    '/admin/profile/my-team': {
      id: '/admin/profile/my-team'
      path: '/my-team'
      fullPath: '/admin/profile/my-team'
      preLoaderRoute: typeof AdminProfileMyTeamRouteImport
      parentRoute: typeof AdminProfileRoute
    }
    '/admin/profile/homepage-photos': {
      id: '/admin/profile/homepage-photos'
      path: '/homepage-photos'
      fullPath: '/admin/profile/homepage-photos'
      preLoaderRoute: typeof AdminProfileHomepagePhotosRouteImport
      parentRoute: typeof AdminProfileRoute
    }
    '/admin/homestays/$homestayId': {
      id: '/admin/homestays/$homestayId'
      path: '/homestays/$homestayId'
      fullPath: '/admin/homestays/$homestayId'
      preLoaderRoute: typeof AdminHomestaysHomestayIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homestay/requests': {
      id: '/admin/homestay/requests'
      path: '/homestay/requests'
      fullPath: '/admin/homestay/requests'
      preLoaderRoute: typeof AdminHomestayRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homestay/pending-bookings': {
      id: '/admin/homestay/pending-bookings'
      path: '/homestay/pending-bookings'
      fullPath: '/admin/homestay/pending-bookings'
      preLoaderRoute: typeof AdminHomestayPendingBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/requests': {
      id: '/admin/experiences/requests'
      path: '/experiences/requests'
      fullPath: '/admin/experiences/requests'
      preLoaderRoute: typeof AdminExperiencesRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/pending-bookings': {
      id: '/admin/experiences/pending-bookings'
      path: '/experiences/pending-bookings'
      fullPath: '/admin/experiences/pending-bookings'
      preLoaderRoute: typeof AdminExperiencesPendingBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/$experienceId': {
      id: '/admin/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/admin/experiences/$experienceId'
      preLoaderRoute: typeof AdminExperiencesExperienceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/homestays/': {
      id: '/admin/reviews/homestays/'
      path: '/reviews/homestays'
      fullPath: '/admin/reviews/homestays/'
      preLoaderRoute: typeof AdminReviewsHomestaysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/experiences/': {
      id: '/admin/reviews/experiences/'
      path: '/reviews/experiences'
      fullPath: '/admin/reviews/experiences/'
      preLoaderRoute: typeof AdminReviewsExperiencesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/cart/checkout/$slug': {
      id: '/dashboard/cart/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/dashboard/cart/checkout/$slug'
      preLoaderRoute: typeof DashboardCartCheckoutSlugRouteImport
      parentRoute: typeof DashboardCartRoute
    }
  }
}

interface AdminProfileRouteChildren {
  AdminProfileHomepagePhotosRoute: typeof AdminProfileHomepagePhotosRoute
  AdminProfileMyTeamRoute: typeof AdminProfileMyTeamRoute
  AdminProfileUsersRoute: typeof AdminProfileUsersRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
}

const AdminProfileRouteChildren: AdminProfileRouteChildren = {
  AdminProfileHomepagePhotosRoute: AdminProfileHomepagePhotosRoute,
  AdminProfileMyTeamRoute: AdminProfileMyTeamRoute,
  AdminProfileUsersRoute: AdminProfileUsersRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
}

const AdminProfileRouteWithChildren = AdminProfileRoute._addFileChildren(
  AdminProfileRouteChildren,
)

interface AdminRouteChildren {
  AdminHomepageEditRoute: typeof AdminHomepageEditRoute
  AdminHomepagePhotosRoute: typeof AdminHomepagePhotosRoute
  AdminHomestayFeaturedRoute: typeof AdminHomestayFeaturedRoute
  AdminProfileRoute: typeof AdminProfileRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminExperiencesExperienceIdRoute: typeof AdminExperiencesExperienceIdRoute
  AdminExperiencesPendingBookingsRoute: typeof AdminExperiencesPendingBookingsRoute
  AdminExperiencesRequestsRoute: typeof AdminExperiencesRequestsRoute
  AdminHomestayPendingBookingsRoute: typeof AdminHomestayPendingBookingsRoute
  AdminHomestayRequestsRoute: typeof AdminHomestayRequestsRoute
  AdminHomestaysHomestayIdRoute: typeof AdminHomestaysHomestayIdRoute
  AdminVipPackagesPackageIdRoute: typeof AdminVipPackagesPackageIdRoute
  AdminVipPendingBookingsRoute: typeof AdminVipPendingBookingsRoute
  AdminVipRequestsRoute: typeof AdminVipRequestsRoute
  AdminActivityIndexRoute: typeof AdminActivityIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminExperiencesIndexRoute: typeof AdminExperiencesIndexRoute
  AdminHomestayOwnersIndexRoute: typeof AdminHomestayOwnersIndexRoute
  AdminHomestayIndexRoute: typeof AdminHomestayIndexRoute
  AdminHomestaysIndexRoute: typeof AdminHomestaysIndexRoute
  AdminHostsIndexRoute: typeof AdminHostsIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminTrustIndexRoute: typeof AdminTrustIndexRoute
  AdminVipOwnersIndexRoute: typeof AdminVipOwnersIndexRoute
  AdminVipPackagesIndexRoute: typeof AdminVipPackagesIndexRoute
  AdminVipIndexRoute: typeof AdminVipIndexRoute
  AdminReviewsExperiencesIndexRoute: typeof AdminReviewsExperiencesIndexRoute
  AdminReviewsHomestaysIndexRoute: typeof AdminReviewsHomestaysIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHomepageEditRoute: AdminHomepageEditRoute,
  AdminHomepagePhotosRoute: AdminHomepagePhotosRoute,
  AdminHomestayFeaturedRoute: AdminHomestayFeaturedRoute,
  AdminProfileRoute: AdminProfileRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminExperiencesExperienceIdRoute: AdminExperiencesExperienceIdRoute,
  AdminExperiencesPendingBookingsRoute: AdminExperiencesPendingBookingsRoute,
  AdminExperiencesRequestsRoute: AdminExperiencesRequestsRoute,
  AdminHomestayPendingBookingsRoute: AdminHomestayPendingBookingsRoute,
  AdminHomestayRequestsRoute: AdminHomestayRequestsRoute,
  AdminHomestaysHomestayIdRoute: AdminHomestaysHomestayIdRoute,
  AdminVipPackagesPackageIdRoute: AdminVipPackagesPackageIdRoute,
  AdminVipPendingBookingsRoute: AdminVipPendingBookingsRoute,
  AdminVipRequestsRoute: AdminVipRequestsRoute,
  AdminActivityIndexRoute: AdminActivityIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminExperiencesIndexRoute: AdminExperiencesIndexRoute,
  AdminHomestayOwnersIndexRoute: AdminHomestayOwnersIndexRoute,
  AdminHomestayIndexRoute: AdminHomestayIndexRoute,
  AdminHomestaysIndexRoute: AdminHomestaysIndexRoute,
  AdminHostsIndexRoute: AdminHostsIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminTrustIndexRoute: AdminTrustIndexRoute,
  AdminVipOwnersIndexRoute: AdminVipOwnersIndexRoute,
  AdminVipPackagesIndexRoute: AdminVipPackagesIndexRoute,
  AdminVipIndexRoute: AdminVipIndexRoute,
  AdminReviewsExperiencesIndexRoute: AdminReviewsExperiencesIndexRoute,
  AdminReviewsHomestaysIndexRoute: AdminReviewsHomestaysIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitiesRouteChildren {
  CitiesSlugRoute: typeof CitiesSlugRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesSlugRoute: CitiesSlugRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface DashboardCartRouteChildren {
  DashboardCartIndexRoute: typeof DashboardCartIndexRoute
  DashboardCartCheckoutSlugRoute: typeof DashboardCartCheckoutSlugRoute
}

const DashboardCartRouteChildren: DashboardCartRouteChildren = {
  DashboardCartIndexRoute: DashboardCartIndexRoute,
  DashboardCartCheckoutSlugRoute: DashboardCartCheckoutSlugRoute,
}

const DashboardCartRouteWithChildren = DashboardCartRoute._addFileChildren(
  DashboardCartRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCancelledRoute: typeof DashboardCancelledRoute
  DashboardCartRoute: typeof DashboardCartRouteWithChildren
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardPastRoute: typeof DashboardPastRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCancelledRoute: DashboardCancelledRoute,
  DashboardCartRoute: DashboardCartRouteWithChildren,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardPastRoute: DashboardPastRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ExperiencesSlugRouteChildren {
  ExperiencesSlugBookRoute: typeof ExperiencesSlugBookRoute
  ExperiencesSlugIndexRoute: typeof ExperiencesSlugIndexRoute
}

const ExperiencesSlugRouteChildren: ExperiencesSlugRouteChildren = {
  ExperiencesSlugBookRoute: ExperiencesSlugBookRoute,
  ExperiencesSlugIndexRoute: ExperiencesSlugIndexRoute,
}

const ExperiencesSlugRouteWithChildren = ExperiencesSlugRoute._addFileChildren(
  ExperiencesSlugRouteChildren,
)

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRouteWithChildren
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRouteWithChildren,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface BookingsBookingIdRouteChildren {
  BookingsBookingIdReviewRoute: typeof BookingsBookingIdReviewRoute
  BookingsBookingIdIndexRoute: typeof BookingsBookingIdIndexRoute
}

const BookingsBookingIdRouteChildren: BookingsBookingIdRouteChildren = {
  BookingsBookingIdReviewRoute: BookingsBookingIdReviewRoute,
  BookingsBookingIdIndexRoute: BookingsBookingIdIndexRoute,
}

const BookingsBookingIdRouteWithChildren =
  BookingsBookingIdRoute._addFileChildren(BookingsBookingIdRouteChildren)

interface HomestayBookingsRouteChildren {
  HomestayBookingsIndexRoute: typeof HomestayBookingsIndexRoute
}

const HomestayBookingsRouteChildren: HomestayBookingsRouteChildren = {
  HomestayBookingsIndexRoute: HomestayBookingsIndexRoute,
}

const HomestayBookingsRouteWithChildren =
  HomestayBookingsRoute._addFileChildren(HomestayBookingsRouteChildren)

interface HomestayPropertiesRouteChildren {
  HomestayPropertiesHomestayIdRoute: typeof HomestayPropertiesHomestayIdRoute
  HomestayPropertiesNewRoute: typeof HomestayPropertiesNewRoute
  HomestayPropertiesIndexRoute: typeof HomestayPropertiesIndexRoute
}

const HomestayPropertiesRouteChildren: HomestayPropertiesRouteChildren = {
  HomestayPropertiesHomestayIdRoute: HomestayPropertiesHomestayIdRoute,
  HomestayPropertiesNewRoute: HomestayPropertiesNewRoute,
  HomestayPropertiesIndexRoute: HomestayPropertiesIndexRoute,
}

const HomestayPropertiesRouteWithChildren =
  HomestayPropertiesRoute._addFileChildren(HomestayPropertiesRouteChildren)

interface HomestaysSlugRouteChildren {
  HomestaysSlugBookRoute: typeof HomestaysSlugBookRoute
  HomestaysSlugIndexRoute: typeof HomestaysSlugIndexRoute
}

const HomestaysSlugRouteChildren: HomestaysSlugRouteChildren = {
  HomestaysSlugBookRoute: HomestaysSlugBookRoute,
  HomestaysSlugIndexRoute: HomestaysSlugIndexRoute,
}

const HomestaysSlugRouteWithChildren = HomestaysSlugRoute._addFileChildren(
  HomestaysSlugRouteChildren,
)

interface HostBookingsRouteChildren {
  HostBookingsBookingIdRoute: typeof HostBookingsBookingIdRoute
  HostBookingsIndexRoute: typeof HostBookingsIndexRoute
}

const HostBookingsRouteChildren: HostBookingsRouteChildren = {
  HostBookingsBookingIdRoute: HostBookingsBookingIdRoute,
  HostBookingsIndexRoute: HostBookingsIndexRoute,
}

const HostBookingsRouteWithChildren = HostBookingsRoute._addFileChildren(
  HostBookingsRouteChildren,
)

interface HostExperiencesRouteChildren {
  HostExperiencesExperienceIdRoute: typeof HostExperiencesExperienceIdRoute
  HostExperiencesNewRoute: typeof HostExperiencesNewRoute
  HostExperiencesIndexRoute: typeof HostExperiencesIndexRoute
}

const HostExperiencesRouteChildren: HostExperiencesRouteChildren = {
  HostExperiencesExperienceIdRoute: HostExperiencesExperienceIdRoute,
  HostExperiencesNewRoute: HostExperiencesNewRoute,
  HostExperiencesIndexRoute: HostExperiencesIndexRoute,
}

const HostExperiencesRouteWithChildren = HostExperiencesRoute._addFileChildren(
  HostExperiencesRouteChildren,
)

interface VipBookingsRouteChildren {
  VipBookingsIndexRoute: typeof VipBookingsIndexRoute
}

const VipBookingsRouteChildren: VipBookingsRouteChildren = {
  VipBookingsIndexRoute: VipBookingsIndexRoute,
}

const VipBookingsRouteWithChildren = VipBookingsRoute._addFileChildren(
  VipBookingsRouteChildren,
)

interface VipListingsRouteChildren {
  VipListingsPackageIdRoute: typeof VipListingsPackageIdRoute
  VipListingsNewRoute: typeof VipListingsNewRoute
  VipListingsIndexRoute: typeof VipListingsIndexRoute
}

const VipListingsRouteChildren: VipListingsRouteChildren = {
  VipListingsPackageIdRoute: VipListingsPackageIdRoute,
  VipListingsNewRoute: VipListingsNewRoute,
  VipListingsIndexRoute: VipListingsIndexRoute,
}

const VipListingsRouteWithChildren = VipListingsRoute._addFileChildren(
  VipListingsRouteChildren,
)

interface VipsSlugRouteChildren {
  VipsSlugIndexRoute: typeof VipsSlugIndexRoute
}

const VipsSlugRouteChildren: VipsSlugRouteChildren = {
  VipsSlugIndexRoute: VipsSlugIndexRoute,
}

const VipsSlugRouteWithChildren = VipsSlugRoute._addFileChildren(
  VipsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CitiesRoute: CitiesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JournalRoute: JournalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountVipApplyRoute: AccountVipApplyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookingsBookingIdRoute: BookingsBookingIdRouteWithChildren,
  HomestayBookingsRoute: HomestayBookingsRouteWithChildren,
  HomestayDashboardRoute: HomestayDashboardRoute,
  HomestayPropertiesRoute: HomestayPropertiesRouteWithChildren,
  HomestaysSlugRoute: HomestaysSlugRouteWithChildren,
  HostBookingsRoute: HostBookingsRouteWithChildren,
  HostDashboardRoute: HostDashboardRoute,
  HostExperiencesRoute: HostExperiencesRouteWithChildren,
  HostProfileRoute: HostProfileRoute,
  HostRevenueRoute: HostRevenueRoute,
  HostReviewsRoute: HostReviewsRoute,
  LegalExperienceTermsRoute: LegalExperienceTermsRoute,
  LegalPaymentPolicyRoute: LegalPaymentPolicyRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  StaysBookingIdRoute: StaysBookingIdRoute,
  VipBookingsRoute: VipBookingsRouteWithChildren,
  VipDashboardRoute: VipDashboardRoute,
  VipListingsRoute: VipListingsRouteWithChildren,
  VipsSlugRoute: VipsSlugRouteWithChildren,
  HomestaysIndexRoute: HomestaysIndexRoute,
  VipsIndexRoute: VipsIndexRoute,
  MemberVipCustomRequestRoute: MemberVipCustomRequestRoute,
  MemberVipPackagesRoute: MemberVipPackagesRoute,
  HomestaysBrowseIndexRoute: HomestaysBrowseIndexRoute,
  MemberVipIndexRoute: MemberVipIndexRoute,
  VipCustomRequestsIndexRoute: VipCustomRequestsIndexRoute,
  VipMembersIndexRoute: VipMembersIndexRoute,
  VipsBrowseIndexRoute: VipsBrowseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
